<?php
require_once 'db.php';
requireAdmin();

/**
 * Pure-PHP database backup (no shell_exec/mysqldump binary dependency -
 * many shared hosts and locked-down XAMPP installs disable shell_exec, so
 * this reads the schema/data over the existing mysqli connection instead).
 * Writes proper UTF-8 (not the UTF-16 issue found in the original
 * database.sql during the audit).
 */
function runBackup($conn, $dbName) {
    $output = "-- Backup of `$dbName` generated " . date('Y-m-d H:i:s') . "\n";
    $output .= "-- Generated by backup_admin.php (pure PHP, UTF-8)\n";
    $output .= "SET NAMES utf8mb4;\nSET FOREIGN_KEY_CHECKS=0;\n\n";

    $tablesResult = mysqli_query($conn, "SHOW TABLES");
    $tables = [];
    while ($row = mysqli_fetch_row($tablesResult)) $tables[] = $row[0];

    foreach ($tables as $table) {
        $output .= "-- ----------------------------\n-- Table: $table\n-- ----------------------------\n";
        $createRow = mysqli_fetch_row(mysqli_query($conn, "SHOW CREATE TABLE `$table`"));
        $output .= "DROP TABLE IF EXISTS `$table`;\n" . $createRow[1] . ";\n\n";

        $dataResult = mysqli_query($conn, "SELECT * FROM `$table`");
        $rowCount = 0;
        while ($row = mysqli_fetch_assoc($dataResult)) {
            $cols = array_keys($row);
            $vals = array_map(function ($v) use ($conn) {
                if ($v === null) return 'NULL';
                return "'" . mysqli_real_escape_string($conn, $v) . "'";
            }, array_values($row));
            $output .= "INSERT INTO `$table` (`" . implode('`,`', $cols) . "`) VALUES (" . implode(',', $vals) . ");\n";
            $rowCount++;
            // Flush periodically to avoid building an enormous string in memory for huge tables
            if ($rowCount % 500 === 0 && !empty($GLOBALS['__backup_fh']) && is_resource($GLOBALS['__backup_fh'])) {
                fwrite($GLOBALS['__backup_fh'], $output);
                $output = '';
            }
        }
        $output .= "\n";
    }
    $output .= "SET FOREIGN_KEY_CHECKS=1;\n";
    return $output;
}

$message = '';
$error = '';

if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['run_backup'])) {
    if (!verifyCsrfToken($_POST['csrf_token'] ?? '')) {
        $error = "የደህንነት ማረጋገጫ አልተሳካም!";
    } else {
        $filename = 'backup_' . date('Ymd_His') . '.sql';
        $path = __DIR__ . '/backups/' . $filename;
        $GLOBALS['__backup_fh'] = fopen($path, 'w');
        if ($GLOBALS['__backup_fh']) {
            $sql = runBackup($conn, DB_NAME);
            fwrite($GLOBALS['__backup_fh'], $sql);
            fclose($GLOBALS['__backup_fh']);
            auditLog($conn, 'database_backup_created', null, null, $filename);
            $message = "ምትኬ ተፈጥሯል: $filename";
        } else {
            $error = "ምትኬ ፋይል መፍጠር አልተቻለም! የ backups/ ማህደር ፍቃድ ያረጋግጡ።";
        }
    }
}

if (isset($_GET['download'])) {
    $safe = basename($_GET['download']); // prevent path traversal
    $path = __DIR__ . '/backups/' . $safe;
    if (preg_match('/^backup_\d{8}_\d{6}\.sql$/', $safe) && file_exists($path)) {
        auditLog($conn, 'database_backup_downloaded', null, null, $safe);
        header('Content-Type: application/sql');
        header('Content-Disposition: attachment; filename="' . $safe . '"');
        header('Content-Length: ' . filesize($path));
        readfile($path);
        exit;
    } else {
        http_response_code(404);
        die('Not found.');
    }
}

if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['delete_backup'])) {
    if (verifyCsrfToken($_POST['csrf_token'] ?? '')) {
        $safe = basename($_POST['filename'] ?? '');
        $path = __DIR__ . '/backups/' . $safe;
        if (preg_match('/^backup_\d{8}_\d{6}\.sql$/', $safe) && file_exists($path)) {
            unlink($path);
            auditLog($conn, 'database_backup_deleted', null, null, $safe);
            $message = "ምትኬ ተሰርዟል።";
        }
    }
}

$backups = glob(__DIR__ . '/backups/backup_*.sql');
rsort($backups);

$nav_active = 'backup_admin';

// Calculate storage stats
$total_backups = count($backups);
$total_bytes = 0;
foreach ($backups as $b) {
    if (file_exists($b)) {
        $total_bytes += filesize($b);
    }
}
$total_size_mb = round($total_bytes / (1024 * 1024), 2);
$latest_backup_time = !empty($backups) ? date('Y-m-d h:i A', filemtime($backups[0])) : 'ምንም የለም';
?>
<!DOCTYPE html>
<html lang="am">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>የመረጃ ቋት ምትኬ | አጸደ ትጉሃን</title>
<?php include 'pwa_head.php'; ?>
<style>
:root {
    --brown-dark: #8B4513;
    --brown-medium: #A52A2A;
    --gold-primary: #FFD700;
    --gold-dark: #DAA520;
    --gold-pale: #FFF8DC;
    --bg-cream: #FAF9F6;
    --card-bg: #FFFFFF;
    --text-main: #1F2937;
    --text-muted: #6B7280;
    --border-color: #E5E7EB;
    --success: #10B981;
    --error: #EF4444;
}

        html.dark-mode,
        html[data-theme="dark"],
        body.dark-mode {
            --bg-cream: #0B1120 !important;
            --bg-light: #0B1120 !important;
            --card-bg: #1E293B !important;
            --card-bg-subtle: #162032 !important;
            --text-main: #F1F5F9 !important;
            --text-muted: #94A3B8 !important;
            --border-color: #334155 !important;
            --border-subtle: #243247 !important;
            --gold-pale: rgba(245, 158, 11, 0.15) !important;
        }

        html.dark-mode body,
        body.dark-mode,
        html[data-theme="dark"] body {
            background-color: #0B1120 !important;
            background: #0B1120 !important;
            color: #F1F5F9 !important;
        }

        html.dark-mode .content-card,
        html.dark-mode .stat-box,
        html.dark-mode .stat-card,
        html.dark-mode .church-card,
        html.dark-mode .class-card,
        html.dark-mode .student-card,
        html.dark-mode .teacher-card,
        html.dark-mode .user-card,
        html.dark-mode .scheme-card,
        html.dark-mode .promotion-box,
        html.dark-mode .sim-summary,
        html.dark-mode .page-hero,
        html.dark-mode .backup-item,
        html.dark-mode .history-card,
        html.dark-mode .semester-banner,
        html.dark-mode .total-summary-card,
        html.dark-mode .table-wrapper,
        html.dark-mode .modal-card,
        html.dark-mode .modal-content,
        body.dark-mode .content-card,
        body.dark-mode .stat-box,
        body.dark-mode .stat-card,
        body.dark-mode .church-card,
        body.dark-mode .class-card,
        body.dark-mode .student-card,
        body.dark-mode .teacher-card,
        body.dark-mode .user-card,
        body.dark-mode .scheme-card,
        body.dark-mode .promotion-box,
        body.dark-mode .sim-summary,
        body.dark-mode .page-hero,
        body.dark-mode .backup-item,
        body.dark-mode .history-card,
        body.dark-mode .semester-banner,
        body.dark-mode .total-summary-card,
        body.dark-mode .table-wrapper,
        body.dark-mode .modal-card,
        body.dark-mode .modal-content,
        [data-theme="dark"] .content-card,
        [data-theme="dark"] .stat-box,
        [data-theme="dark"] .stat-card,
        [data-theme="dark"] .church-card,
        [data-theme="dark"] .class-card,
        [data-theme="dark"] .student-card,
        [data-theme="dark"] .teacher-card,
        [data-theme="dark"] .user-card,
        [data-theme="dark"] .scheme-card,
        [data-theme="dark"] .promotion-box,
        [data-theme="dark"] .sim-summary,
        [data-theme="dark"] .page-hero,
        [data-theme="dark"] .backup-item,
        [data-theme="dark"] .history-card,
        [data-theme="dark"] .semester-banner,
        [data-theme="dark"] .total-summary-card,
        [data-theme="dark"] .table-wrapper,
        [data-theme="dark"] .modal-card,
        [data-theme="dark"] .modal-content {
            background-color: #1E293B !important;
            background: #1E293B !important;
            color: #F1F5F9 !important;
            border-color: #334155 !important;
            box-shadow: 0 4px 20px rgba(0, 0, 0, 0.4) !important;
        }

        html.dark-mode .form-input,
        html.dark-mode .filter-input,
        html.dark-mode .form-control,
        html.dark-mode .search-input,
        html.dark-mode .passmark-input,
        html.dark-mode .filter-select,
        html.dark-mode select,
        body.dark-mode .form-input,
        body.dark-mode .filter-input,
        body.dark-mode .form-control,
        body.dark-mode .search-input,
        body.dark-mode .passmark-input,
        body.dark-mode .filter-select,
        body.dark-mode select,
        [data-theme="dark"] .form-input,
        [data-theme="dark"] .filter-input,
        [data-theme="dark"] .form-control,
        [data-theme="dark"] .search-input,
        [data-theme="dark"] .passmark-input,
        [data-theme="dark"] .filter-select,
        [data-theme="dark"] select {
            background-color: #0F172A !important;
            background: #0F172A !important;
            color: #F8FAFC !important;
            border-color: #475569 !important;
        }

        html.dark-mode th,
        body.dark-mode th,
        [data-theme="dark"] th {
            background-color: #0F172A !important;
            background: #0F172A !important;
            color: #FCD34D !important;
            border-color: #334155 !important;
        }

        html.dark-mode td,
        body.dark-mode td,
        [data-theme="dark"] td {
            background-color: #1E293B !important;
            color: #E2E8F0 !important;
            border-color: #334155 !important;
        }

        html.dark-mode tr:hover td,
        body.dark-mode tr:hover td,
        [data-theme="dark"] tr:hover td {
            background-color: #26354A !important;
        }

        html.dark-mode .stat-val,
        html.dark-mode .stat-value,
        html.dark-mode .stat-num,
        body.dark-mode .stat-val,
        body.dark-mode .stat-value,
        body.dark-mode .stat-num,
        [data-theme="dark"] .stat-val,
        [data-theme="dark"] .stat-value,
        [data-theme="dark"] .stat-num {
            color: #FCD34D !important;
        }

        html.dark-mode .stat-lbl,
        html.dark-mode .stat-label,
        body.dark-mode .stat-lbl,
        body.dark-mode .stat-label,
        [data-theme="dark"] .stat-lbl,
        [data-theme="dark"] .stat-label {
            color: #94A3B8 !important;
        }


* { margin: 0; padding: 0; box-sizing: border-box; font-family: 'Segoe UI', system-ui, -apple-system, sans-serif; }
body { background: var(--bg-cream); color: var(--text-main); min-height: 100vh; }

.main-container { max-width: 1000px; margin: 12px auto; padding: 0 10px 40px; }

/* Page Header Card */
.page-header-card {
    background: linear-gradient(135deg, #8B4513 0%, #A52A2A 100%);
    border-radius: 16px;
    padding: 18px 16px;
    color: white;
    margin-bottom: 24px;
    box-shadow: 0 8px 24px rgba(139, 69, 19, 0.18);
    display: flex;
    justify-content: space-between;
    align-items: center;
    flex-wrap: wrap;
    gap: 16px;
    position: relative;
    overflow: hidden;
}
.page-header-card::after {
    content: '💾';
    position: absolute;
    right: 20px;
    bottom: -15px;
    font-size: 100px;
    opacity: 0.12;
    pointer-events: none;
}
.header-info h1 {
    font-size: 22px;
    font-weight: 800;
    color: var(--gold-primary);
    display: flex;
    align-items: center;
    gap: 10px;
    margin-bottom: 6px;
}
.header-info p {
    font-size: 13.5px;
    color: rgba(255, 255, 255, 0.9);
    max-width: 600px;
    line-height: 1.5;
}

/* Stats Row */
.stats-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
    gap: 16px;
    margin-bottom: 24px;
}
.stat-box {
    background: var(--card-bg);
    border: 1px solid var(--border-color);
    border-radius: 14px;
    padding: 16px 20px;
    display: flex;
    align-items: center;
    gap: 16px;
    box-shadow: 0 2px 8px rgba(0,0,0,0.04);
}
.stat-icon {
    width: 48px;
    height: 48px;
    border-radius: 12px;
    background: var(--gold-pale);
    color: var(--brown-dark);
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 22px;
    flex-shrink: 0;
}
.stat-data .stat-val {
    font-size: 22px;
    font-weight: 800;
    color: var(--brown-dark);
}
.stat-data .stat-lbl {
    font-size: 12px;
    color: var(--text-muted);
    font-weight: 600;
}

/* Alerts */
.message {
    padding: 14px 18px;
    border-radius: 12px;
    margin-bottom: 20px;
    display: flex;
    align-items: center;
    gap: 10px;
    font-weight: 600;
    font-size: 14px;
    box-shadow: 0 2px 8px rgba(0,0,0,0.05);
}
.message.success { background: #DCFCE7; color: #166534; border-left: 4px solid var(--success); }
.message.error { background: #FEE2E2; color: #991B1B; border-left: 4px solid var(--error); }

/* Create Card */
.action-card {
    background: var(--card-bg);
    border-radius: 16px;
    padding: 24px;
    margin-bottom: 24px;
    border: 1px solid var(--border-color);
    box-shadow: 0 4px 14px rgba(0,0,0,0.05);
    display: flex;
    justify-content: space-between;
    align-items: stretch;
    flex-wrap: wrap;
    gap: 20px;
}
.action-card-text h3 {
    color: var(--brown-dark);
    font-size: 17px;
    margin-bottom: 6px;
    display: flex;
    align-items: center;
    gap: 8px;
}
.action-card-text p {
    color: var(--text-muted);
    font-size: 13.5px;
    max-width: 550px;
    line-height: 1.5;
}
.btn-create-backup {
    background: linear-gradient(135deg, var(--gold-primary) 0%, var(--gold-dark) 100%);
    color: var(--brown-dark);
    border: none;
    padding: 13px 26px;
    border-radius: 12px;
    font-weight: 800;
    font-size: 15px;
    cursor: pointer;
    display: inline-flex;
    align-items: center;
    gap: 8px;
    transition: all 0.25s ease;
    box-shadow: 0 4px 12px rgba(218, 165, 32, 0.25);
    white-space: nowrap;
}
.btn-create-backup:hover {
    transform: translateY(-2px);
    box-shadow: 0 6px 16px rgba(218, 165, 32, 0.35);
}
.btn-create-backup:disabled {
    opacity: 0.7;
    cursor: not-allowed;
    transform: none;
}

/* Backups List Card */
.list-card {
    background: var(--card-bg);
    border-radius: 16px;
    border: 1px solid var(--border-color);
    box-shadow: 0 4px 16px rgba(0,0,0,0.05);
    overflow: hidden;
}
.list-card-header {
    padding: 18px 24px;
    background: #F9FAFB;
    border-bottom: 1px solid var(--border-color);
    display: flex;
    justify-content: space-between;
    align-items: center;
}
.list-card-header h3 {
    font-size: 16px;
    color: var(--brown-dark);
    display: flex;
    align-items: center;
    gap: 8px;
}
.backup-item {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    padding: 16px 24px;
    border-bottom: 1px solid #F3F4F6;
    transition: background 0.15s ease;
    gap: 12px;
}
.backup-item:last-child { border-bottom: none; }
.backup-item:hover { background: rgba(255, 215, 0, 0.03); }

.backup-file-info {
    display: flex;
    align-items: center;
    gap: 14px;
}
.file-badge {
    width: 44px;
    height: 44px;
    border-radius: 10px;
    background: #EFF6FF;
    color: #2563EB;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 22px;
    flex-shrink: 0;
}
.file-name {
    font-weight: 700;
    font-size: 14px;
    color: var(--text-main);
    word-break: break-all;
    font-family: monospace;
}
.file-meta {
    font-size: 12px;
    color: var(--text-muted);
    display: flex;
    gap: 12px;
    margin-top: 3px;
    flex-wrap: wrap;
}
.file-meta span {
    display: inline-flex;
    align-items: center;
    gap: 4px;
}

.backup-actions {
    display: flex;
    align-items: center;
    gap: 8px;
    flex-shrink: 0;
}
.btn-dl {
    background: #10B981;
    color: white;
    padding: 8px 16px;
    border-radius: 8px;
    text-decoration: none;
    font-weight: 700;
    font-size: 13px;
    display: inline-flex;
    align-items: center;
    gap: 6px;
    transition: all 0.2s ease;
}
.btn-dl:hover {
    background: #059669;
    transform: translateY(-1px);
}
.btn-del {
    background: #FEE2E2;
    color: #DC2626;
    border: none;
    padding: 8px 14px;
    border-radius: 8px;
    font-weight: 700;
    font-size: 13px;
    cursor: pointer;
    display: inline-flex;
    align-items: center;
    gap: 4px;
    transition: all 0.2s ease;
}
.btn-del:hover {
    background: #EF4444;
    color: white;
}

/* Empty State */
.empty-state {
    text-align: center;
    padding: 50px 20px;
    color: var(--text-muted);
}
.empty-icon {
    font-size: 48px;
    margin-bottom: 12px;
    opacity: 0.7;
}

@media (max-width: 650px) {
    .main-container { padding: 0 10px 40px; margin: 12px auto; }
    .page-header-card { padding: 18px 16px; }
    .action-card { flex-direction: column; align-items: stretch; text-align: center; }
    .btn-create-backup { width: 100%; justify-content: center; }
    .backup-item { flex-direction: column; align-items: flex-start; gap: 12px; }
    .backup-actions { width: 100%; justify-content: flex-end; }
    .btn-dl, .btn-del { flex: 1; justify-content: center; min-height: 40px; }
}
</style>
</head>
<body>
<?php include 'mobile_nav.php'; ?>

<div class="main-container">
    <!-- Header -->
    <div class="page-header-card">
        <div class="header-info">
            <h1>💾 የመረጃ ቋት ምትኬ (Database Backup)</h1>
            <p>የተማሪዎችን ውጤት፣ መምህራንን፣ ክፍሎችን እና ሁሉንም መረጃዎች በደህና ሁኔታ ምትኬ ወስደው ያስቀምጡ።</p>
        </div>
    </div>

    <?php if ($message): ?>
    <div class="message success">✅ <?php echo htmlspecialchars($message); ?></div>
    <?php endif; ?>

    <?php if ($error): ?>
    <div class="message error">⚠️ <?php echo htmlspecialchars($error); ?></div>
    <?php endif; ?>

    <!-- Stats -->
    <div class="stats-grid">
        <div class="stat-box">
            <div class="stat-icon">📁</div>
            <div class="stat-data">
                <div class="stat-val"><?php echo $total_backups; ?></div>
                <div class="stat-lbl">ያሉ ምትኬ ፋይሎች</div>
            </div>
        </div>
        <div class="stat-box">
            <div class="stat-icon">📊</div>
            <div class="stat-data">
                <div class="stat-val"><?php echo $total_size_mb; ?> MB</div>
                <div class="stat-lbl">ጠቅላላ የተያዘ ቦታ</div>
            </div>
        </div>
        <div class="stat-box">
            <div class="stat-icon">🕒</div>
            <div class="stat-data">
                <div class="stat-val" style="font-size: 14px;"><?php echo $latest_backup_time; ?></div>
                <div class="stat-lbl">የመጨረሻው ምትኬ</div>
            </div>
        </div>
    </div>

    <!-- Create Action -->
    <div class="action-card">
        <div class="action-card-text">
            <h3>⚡ አዲስ ምትኬ መፍጠር</h3>
            <p>ይህ ትዕዛዝ ሙሉውን የመረጃ ቋት ሰንጠረዦች በUTF-8 ቅርጸት ወደ <code>backups/</code> ማህደር ያዘጋጃል።</p>
        </div>
        <form method="POST" onsubmit="handleBackupSubmit(this)">
            <?php echo csrfField(); ?>
            <button type="submit" name="run_backup" id="btnBackup" class="btn-create-backup">
                💾 አዲስ ምትኬ ፍጠር
            </button>
        </form>
    </div>

    <!-- Backups List -->
    <div class="list-card">
        <div class="list-card-header">
            <h3>🗄️ የተቀመጡ ምትኬዎች ዝርዝር (<?php echo $total_backups; ?>)</h3>
        </div>

        <?php if (empty($backups)): ?>
        <div class="empty-state">
            <div class="empty-icon">📂</div>
            <div style="font-size: 15px; font-weight: 600;">ምንም የተቀመጠ ምትኬ ፋይል የለም።</div>
            <p style="font-size: 13px; margin-top: 6px;">ከላይ ያለውን "አዲስ ምትኬ ፍጠር" የሚለውን በመጫን አዲስ ምትኬ መውሰድ ይችላሉ።</p>
        </div>
        <?php else: foreach ($backups as $b):
            $fname = basename($b);
            $size = round(filesize($b) / 1024, 1);
            $time = date('Y-m-d h:i A', filemtime($b));
        ?>
        <div class="backup-item">
            <div class="backup-file-info">
                <div class="file-badge">🗃️</div>
                <div>
                    <div class="file-name"><?php echo htmlspecialchars($fname); ?></div>
                    <div class="file-meta">
                        <span>📅 <?php echo $time; ?></span>
                        <span>⚖️ <?php echo $size; ?> KB</span>
                    </div>
                </div>
            </div>
            <div class="backup-actions">
                <a href="?download=<?php echo urlencode($fname); ?>" class="btn-dl">
                    ⬇️ አውርድ
                </a>
                <form method="POST" style="display:inline;" onsubmit="return confirm('እርግጠኛ ነዎት ይህን ምትኬ ፋይል [<?php echo htmlspecialchars($fname); ?>] መሰረዝ ይፈልጋሉ?')">
                    <?php echo csrfField(); ?>
                    <input type="hidden" name="filename" value="<?php echo htmlspecialchars($fname); ?>">
                    <button type="submit" name="delete_backup" class="btn-del" title="ሰርዝ">
                        🗑️ ሰርዝ
                    </button>
                </form>
            </div>
        </div>
        <?php endforeach; endif; ?>
    </div>
</div>

<script>
function handleBackupSubmit(form) {
    var btn = document.getElementById('btnBackup');
    if (btn) {
        btn.disabled = true;
        btn.innerHTML = '⏳ ምትኬ እየተፈጠረ ነው...';
    }
}
</script>
</body>
</html>
<?php mysqli_close($conn); ?>
