<?php
require_once 'db.php';
requireAdmin();

/**
 * Pure-PHP database backup (no shell_exec/mysqldump binary dependency -
 * many shared hosts and locked-down XAMPP installs disable shell_exec, so
 * this reads the schema/data over the existing mysqli connection instead).
 * Writes proper UTF-8 (not the UTF-16 issue found in the original
 * database.sql during the audit).
 */
function runBackup($conn, $dbName) {
    $output = "-- Backup of `$dbName` generated " . date('Y-m-d H:i:s') . "\n";
    $output .= "-- Generated by backup_admin.php (pure PHP, UTF-8)\n";
    $output .= "SET NAMES utf8mb4;\nSET FOREIGN_KEY_CHECKS=0;\n\n";

    $tablesResult = mysqli_query($conn, "SHOW TABLES");
    $tables = [];
    while ($row = mysqli_fetch_row($tablesResult)) $tables[] = $row[0];

    foreach ($tables as $table) {
        $output .= "-- ----------------------------\n-- Table: $table\n-- ----------------------------\n";
        $createRow = mysqli_fetch_row(mysqli_query($conn, "SHOW CREATE TABLE `$table`"));
        $output .= "DROP TABLE IF EXISTS `$table`;\n" . $createRow[1] . ";\n\n";

        $dataResult = mysqli_query($conn, "SELECT * FROM `$table`");
        $rowCount = 0;
        while ($row = mysqli_fetch_assoc($dataResult)) {
            $cols = array_keys($row);
            $vals = array_map(function ($v) use ($conn) {
                if ($v === null) return 'NULL';
                return "'" . mysqli_real_escape_string($conn, $v) . "'";
            }, array_values($row));
            $output .= "INSERT INTO `$table` (`" . implode('`,`', $cols) . "`) VALUES (" . implode(',', $vals) . ");\n";
            $rowCount++;
            // Flush periodically to avoid building an enormous string in memory for huge tables
            if ($rowCount % 500 === 0 && !empty($GLOBALS['__backup_fh']) && is_resource($GLOBALS['__backup_fh'])) {
                fwrite($GLOBALS['__backup_fh'], $output);
                $output = '';
            }
        }
        $output .= "\n";
    }
    $output .= "SET FOREIGN_KEY_CHECKS=1;\n";
    return $output;
}

$message = '';
$error = '';

if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['run_backup'])) {
    if (!verifyCsrfToken($_POST['csrf_token'] ?? '')) {
        $error = "የደህንነት ማረጋገጫ አልተሳካም!";
    } else {
        $filename = 'backup_' . date('Ymd_His') . '.sql';
        $path = __DIR__ . '/backups/' . $filename;
        $GLOBALS['__backup_fh'] = fopen($path, 'w');
        if ($GLOBALS['__backup_fh']) {
            $sql = runBackup($conn, DB_NAME);
            fwrite($GLOBALS['__backup_fh'], $sql);
            fclose($GLOBALS['__backup_fh']);
            auditLog($conn, 'database_backup_created', null, null, $filename);
            $message = "ምትኬ ተፈጥሯል: $filename";
        } else {
            $error = "ምትኬ ፋይል መፍጠር አልተቻለም! የ backups/ ማህደር ፍቃድ ያረጋግጡ።";
        }
    }
}

if (isset($_GET['download'])) {
    $safe = basename($_GET['download']); // prevent path traversal
    $path = __DIR__ . '/backups/' . $safe;
    if (preg_match('/^backup_\d{8}_\d{6}\.sql$/', $safe) && file_exists($path)) {
        auditLog($conn, 'database_backup_downloaded', null, null, $safe);
        header('Content-Type: application/sql');
        header('Content-Disposition: attachment; filename="' . $safe . '"');
        header('Content-Length: ' . filesize($path));
        readfile($path);
        exit;
    } else {
        http_response_code(404);
        die('Not found.');
    }
}

if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['delete_backup'])) {
    if (verifyCsrfToken($_POST['csrf_token'] ?? '')) {
        $safe = basename($_POST['filename'] ?? '');
        $path = __DIR__ . '/backups/' . $safe;
        if (preg_match('/^backup_\d{8}_\d{6}\.sql$/', $safe) && file_exists($path)) {
            unlink($path);
            auditLog($conn, 'database_backup_deleted', null, null, $safe);
            $message = "ምትኬ ተሰርዟል።";
        }
    }
}

$backups = glob(__DIR__ . '/backups/backup_*.sql');
rsort($backups);

$nav_active = 'backup_admin';
?>
<!DOCTYPE html>
<html lang="am">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>ምትኬ | አጸደ ትጉሃን</title>
<?php include 'pwa_head.php'; ?>
<style>
:root { --brown-dark:#8B4513; --gold-primary:#FFD700; --success:#10B981; --error:#EF4444; }
* { margin:0; padding:0; box-sizing:border-box; font-family:'Segoe UI',sans-serif; }
body { background:#FAF9F6; }
.main-container { max-width:800px; margin:20px auto; padding:0 15px 60px; }
.card { background:white; border-radius:14px; padding:20px; margin-bottom:20px; box-shadow:0 4px 12px rgba(0,0,0,0.08); }
.message { padding:12px 15px; border-radius:8px; margin-bottom:15px; }
.success { background:#D1FAE5; color:var(--success); } .error { background:#FEE2E2; color:var(--error); }
.btn { background:var(--gold-primary); color:var(--brown-dark); border:none; padding:12px 24px; border-radius:10px; font-weight:700; cursor:pointer; font-size:15px; }
.backup-row { display:flex; justify-content:space-between; align-items:center; padding:12px 5px; border-bottom:1px solid #eee; gap:10px; flex-wrap:wrap; }
.backup-row:last-child { border-bottom:none; }
.btn-sm { padding:6px 14px; border-radius:8px; font-size:13px; text-decoration:none; font-weight:600; }
.btn-download { background:var(--success); color:white; }
.btn-delete { background:var(--error); color:white; border:none; cursor:pointer; }
@media (max-width: 600px) {
    .main-container { padding: 0 10px 40px; margin: 12px auto; }
    .card { padding: 15px 12px; }
    .btn { width: 100%; justify-content: center; font-size: 14px; min-height: 44px; }
    .backup-row { flex-direction: column; align-items: flex-start; gap: 8px; }
    .backup-row > div:first-child { width: 100%; word-break: break-all; }
    .backup-row > div:last-child { width: 100%; display: flex; justify-content: flex-end; gap: 8px; }
}
</style>
</head>
<body>
<?php include 'mobile_nav.php'; ?>
<div class="main-container">
    <?php if ($message): ?><div class="message success">✅ <?php echo htmlspecialchars($message); ?></div><?php endif; ?>
    <?php if ($error): ?><div class="message error">⚠️ <?php echo htmlspecialchars($error); ?></div><?php endif; ?>

    <div class="card">
        <h2 style="color:var(--brown-dark); margin-bottom:10px;">💾 የመረጃ ቋት ምትኬ</h2>
        <p style="color:#777; font-size:14px; margin-bottom:15px;">
            ሙሉ የመረጃ ቋት ምትኬ ይፈጥራል (ሁሉንም ሠንጠረዦች እና መረጃ)። ፋይሉ በ<code>backups/</code> ማህደር ውስጥ ይቀመጣል -
            ከድር በቀጥታ ሊደረስበት አይችልም (ለአስተዳዳሪ ብቻ በዚህ ገጽ በኩል ማውረድ ይቻላል)።
        </p>
        <form method="POST">
            <?php echo csrfField(); ?>
            <button type="submit" name="run_backup" class="btn">💾 አዲስ ምትኬ ፍጠር</button>
        </form>
    </div>

    <div class="card">
        <h2 style="color:var(--brown-dark); margin-bottom:10px;">📁 ያሉ ምትኬዎች (<?php echo count($backups); ?>)</h2>
        <?php if (empty($backups)): ?>
            <p style="color:#999; text-align:center; padding:20px;">ምንም ምትኬ የለም።</p>
        <?php else: foreach ($backups as $b):
            $fname = basename($b);
            $size = round(filesize($b) / 1024, 1);
            $time = date('Y-m-d H:i', filemtime($b));
        ?>
        <div class="backup-row">
            <div><strong><?php echo htmlspecialchars($fname); ?></strong><div style="font-size:12px; color:#999;"><?php echo $time; ?> · <?php echo $size; ?> KB</div></div>
            <div>
                <a href="?download=<?php echo urlencode($fname); ?>" class="btn-sm btn-download">⬇️ አውርድ</a>
                <form method="POST" style="display:inline;" onsubmit="return confirm('ይህን ምትኬ መሰረዝ እርግጠኛ ነዎት?')">
                    <?php echo csrfField(); ?>
                    <input type="hidden" name="filename" value="<?php echo htmlspecialchars($fname); ?>">
                    <button type="submit" name="delete_backup" class="btn-sm btn-delete">🗑️</button>
                </form>
            </div>
        </div>
        <?php endforeach; endif; ?>
    </div>
</div>
</body>
</html>
<?php mysqli_close($conn); ?>
